# 내 PC(local) 환경에서만 적용될 설정

spring:
  # application.yml의 datasource 설정을 이 내용으로 덮어씁니다.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb # 메모리 기반 H2 DB 사용
    username: sa
    password:

  jpa:
    # H2 DB는 ddl-auto: create 로 설정하는 것이 편합니다.
    hibernate:
      ddl-auto: create
    # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console